server:
  port: 9100
spring:
  application:
    name: cloud-im-server

# netty配置
netty:
  #host
  url: localhost
  # 端口号
  port: 12345
  # 最大线程数
  maxThreads: 1024
  # 数据包的最大长度
  max_frame_length: 65535